import "@/styles/globals.css";
import type { Metadata } from "next";


import ReduxProvider from "@/redux/Provider";

import { outfit } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "UMscope Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit} `}>
        
<ReduxProvider>
<div className="font-outfit">
{children}
          
          </div>
  
</ReduxProvider>

      </body>
    </html>
  );
}
