import "@/styles/globals.css";
import '@mantine/core/styles.css';
import type { Metadata } from "next";


import ReduxProvider from "@/redux/Provider";

import { outfit } from "@/utils/fonts";
import { MantineProvider } from "@mantine/core";
import { theme } from "@/theme/app";


export const metadata: Metadata = {
  title: "UMscope Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit} `}>
        
<ReduxProvider>
  <MantineProvider
  withCssVariables

  withGlobalClasses
  theme={theme}

  >
<div className="font-outfit">
{children}
          
          </div>
          </MantineProvider>
</ReduxProvider>

      </body>
    </html>
  );
}
